version: '2.1'

services:
  db:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    env_file: .db-env
    volumes:
      - ./data:/var/lib/mysql
  app:
    image: windwardapps
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:2200 project.wsgi
    ports:
      - 2200:2200
    env_file: .app-env
    volumes:
      - ./logs:/logs
      - ./project:/app/project
    depends_on:
      - db
