version: '3'

services:
  db:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    env_file: .db-env
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - app-network
  app:
    image: windwardapps
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:2200 project.wsgi
    env_file: .app-env
    ports:
      - "2200:2200"
    volumes:
      - ./logs:/logs
      - ./project:/app/project
      - ./static:/app/static
    depends_on:
      - db
    networks:
      - app-network
      - external-net
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20
networks:
  app-network: {}
  external-net:
    external:
      name: external-net
