# Generated by Django 2.0.2 on 2018-05-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='headline',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
